import React, { useEffect, useState } from 'react';
import Cookies from 'js-cookie'; // Import 'js-cookie' library
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isLoggedIn, setIsLoggedIn] = useState<boolean>(false);

  useEffect(() => {
    // Fetch authentication status from cookies or local storage
    const storedAuthStatus = Cookies.get('isLoggedIn'); 

    if (storedAuthStatus === 'true') {
      setIsLoggedIn(true);
    }
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        {isLoggedIn ? (
          // Render content for logged-in users
          <div>{children}</div>
        ) : (
          // Render content for non-logged-in users (e.g., login form)
          <div>
            {/* You can render a login form or a message here */}
            <p>Please log in to access the content.</p>
          </div>
        )}
      </body>
    </html>
  );
}
